CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# KLOR OLED Display config
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
# CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# CONFIG_ZMK_USB_LOGGING=y
